//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alipay
    {
        public int id { get; set; }
        public System.DateTime notify_time { get; set; }
        public string notify_type { get; set; }
        public string sign_type { get; set; }
        public string notify_id { get; set; }
        public string sign { get; set; }
        public string out_trade_no { get; set; }
        public string subject { get; set; }
        public string payment_type { get; set; }
        public string trade_no { get; set; }
        public string trade_status { get; set; }
        public string seller_id { get; set; }
        public string seller_email { get; set; }
        public string buyer_id { get; set; }
        public string buyer_email { get; set; }
        public Nullable<decimal> total_fee { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> gmt_create { get; set; }
        public Nullable<System.DateTime> gmt_payment { get; set; }
        public string is_total_fee_adjust { get; set; }
        public string use_coupon { get; set; }
        public string discount { get; set; }
        public string refund_status { get; set; }
        public Nullable<System.DateTime> gmt_refund { get; set; }
    }
}
