//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Areas
    {
        public Areas()
        {
            this.Airports = new HashSet<Airports>();
            this.Goods = new HashSet<Goods>();
        }
    
        public int area_id { get; set; }
        public Nullable<int> province { get; set; }
        public Nullable<int> city { get; set; }
        public Nullable<int> area { get; set; }
        public string address { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string location { get; set; }
        public string img { get; set; }
    
        public virtual ICollection<Airports> Airports { get; set; }
        public virtual ICollection<Goods> Goods { get; set; }
    }
}
