//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrys
    {
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string id_card { get; set; }
        public string address { get; set; }
        public string model { get; set; }
        public string start { get; set; }
        public string end { get; set; }
        public string desci { get; set; }
        public System.DateTime created_at { get; set; }
        public string typename { get; set; }
        public byte type { get; set; }
        public int user_id { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
