//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public Goods()
        {
            this.Orders = new HashSet<Orders>();
            this.SellerMessage = new HashSet<SellerMessage>();
            this.GoodImages = new HashSet<GoodImages>();
        }
    
        public int good_id { get; set; }
        public int seller_id { get; set; }
        public int area_id { get; set; }
        public int type_id { get; set; }
        public string name { get; set; }
        public string model { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> market_price { get; set; }
        public string production_time { get; set; }
        public Nullable<short> is_lock { get; set; }
        public Nullable<int> visited { get; set; }
        public Nullable<int> collected { get; set; }
        public Nullable<int> saled { get; set; }
        public Nullable<int> comments { get; set; }
        public string col1 { get; set; }
        public string col2 { get; set; }
        public string col3 { get; set; }
        public string col4 { get; set; }
        public string col5 { get; set; }
        public string col6 { get; set; }
        public string col7 { get; set; }
        public string col8 { get; set; }
        public string col9 { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string img { get; set; }
        public string desci { get; set; }
        public string col10 { get; set; }
        public string col11 { get; set; }
        public Nullable<int> parent { get; set; }
        public string unit { get; set; }
        public Nullable<int> priased { get; set; }
        public Nullable<int> shared { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual GoodTypes GoodTypes { get; set; }
        public virtual Sellers Sellers { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<SellerMessage> SellerMessage { get; set; }
        public virtual ICollection<GoodImages> GoodImages { get; set; }
    }
}
