//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodComments
    {
        public GoodComments()
        {
            this.GoodCommentReplys = new HashSet<GoodCommentReplys>();
            this.GoodCommentImages = new HashSet<GoodCommentImages>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string body { get; set; }
        public System.DateTime created_at { get; set; }
        public int user_id { get; set; }
        public int praised { get; set; }
        public int replys { get; set; }
        public int good_id { get; set; }
        public short is_lock { get; set; }
    
        public virtual ICollection<GoodCommentReplys> GoodCommentReplys { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<GoodCommentImages> GoodCommentImages { get; set; }
    }
}
