//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class planeEntities : DbContext
    {
        public planeEntities()
            : base("name=planeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Airports> Airports { get; set; }
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<GoodTypes> GoodTypes { get; set; }
        public virtual DbSet<Levels> Levels { get; set; }
        public virtual DbSet<LoginLogs> LoginLogs { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Places> Places { get; set; }
        public virtual DbSet<Sellers> Sellers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<SellerGroup> SellerGroup { get; set; }
        public virtual DbSet<OrderType> OrderType { get; set; }
        public virtual DbSet<SellerMessage> SellerMessage { get; set; }
        public virtual DbSet<Ads> Ads { get; set; }
        public virtual DbSet<GoodCommentReplys> GoodCommentReplys { get; set; }
        public virtual DbSet<GoodComments> GoodComments { get; set; }
        public virtual DbSet<MessageCommentReplys> MessageCommentReplys { get; set; }
        public virtual DbSet<MessageComments> MessageComments { get; set; }
        public virtual DbSet<GoodImages> GoodImages { get; set; }
        public virtual DbSet<SellerImage> SellerImage { get; set; }
        public virtual DbSet<GoodCommentImages> GoodCommentImages { get; set; }
        public virtual DbSet<MessageCommentImages> MessageCommentImages { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<Entrys> Entrys { get; set; }
        public virtual DbSet<UserCommentImages> UserCommentImages { get; set; }
        public virtual DbSet<UserCommentReplys> UserCommentReplys { get; set; }
        public virtual DbSet<UserComments> UserComments { get; set; }
    }
}
