//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerGroup
    {
        public SellerGroup()
        {
            this.Sellers = new HashSet<Sellers>();
        }
    
        public int sellerGroup_id { get; set; }
        public string name { get; set; }
        public string content { get; set; }
        public Nullable<int> parent { get; set; }
    
        public virtual ICollection<Sellers> Sellers { get; set; }
    }
}
