//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sellers
    {
        public Sellers()
        {
            this.Airports = new HashSet<Airports>();
            this.Goods = new HashSet<Goods>();
            this.SellerMessage = new HashSet<SellerMessage>();
            this.SellerImage = new HashSet<SellerImage>();
        }
    
        public int seller_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public Nullable<short> is_lock { get; set; }
        public string qq { get; set; }
        public string wx { get; set; }
        public string address { get; set; }
        public string img { get; set; }
        public string desci { get; set; }
        public Nullable<int> plants { get; set; }
        public Nullable<int> visited { get; set; }
        public Nullable<int> collected { get; set; }
        public Nullable<int> saled { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> group_id { get; set; }
    
        public virtual ICollection<Airports> Airports { get; set; }
        public virtual ICollection<Goods> Goods { get; set; }
        public virtual SellerGroup SellerGroup { get; set; }
        public virtual ICollection<SellerMessage> SellerMessage { get; set; }
        public virtual ICollection<SellerImage> SellerImage { get; set; }
    }
}
